"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['hnreader.py']
DATA_FILES = ['y22w.png', 'template.html']
OPTIONS = {'argv_emulation': True, 'includes': ['PySide.QtNetwork', 'lxml._elementpath', 'pygments.styles.default']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
